### ISSUE TITLE
Selecting a subset of a DenseVector returns mutable.Vector

### ISSUE THREAD

**Issue by afwlehmann** [scalala/Scalala#10]
Whereas e.g. m(0 until N, ::) for a given DenseMatrix m returns a DenseMatrix, the same doesn't hold for DenseVectors as v(0 until N) for a given DenseVector v returns a mutable.Vector.
I'm not sure whether this is really an issue, it just came unexpected to me.

**Comment by dramage** [comment]
This can be special cased for ranges, which can be represented as a transformation of the underlying offset and stride, committed:

https://github.com/scalala/Scalala/commit/586d223e315c49275659f73afadfe0cd49af8ed4

Indexing by a general Seq has to return a wrapped slice view as you saw, because it can't be expressed with offset and stride.  So this works on DenseVectorCol and DenseVectorRow only.
