### ISSUE TITLE
sha1 for http://repo.scalanlp.org/repo/netlib/netlib-java/0.9.3/netlib-java-0.9.3.pom

### ISSUE THREAD

**Issue by lancelet** [scalala/Scalala#26]
Hi,

I'm upgrading some of my projects to use xsbt 0.10.0.  When the new sbt pulls down dependencies, it seems to be more thorough about checking sha hashes than previous versions.  It complains that:

[warn]  problem while downloading module descriptor: http://repo.scalanlp.org/repo/netlib/netlib-java/0.9.3/netlib-java-0.9.3.pom: invalid sha1: expected=c246e1405f1a6b6181bc32c4fa18b19bce32accb computed=628415b2a48a2d75ede58a78f2aa2504c1acdff3 (399ms)

Is it possible to get this sha1 updated?

Thanks,

Jonathan Merritt.

**Comment by lancelet** [comment]
A work-around is to run `sbt update` from a fresh Scalala checkout, to pull netlib-java into the Ivy cache.  Then, xsbt 0.10.0 will use the cached version and won't check the hash.

**Comment by dlwh** [comment]
I tried changing it. Could you verify?

-- David

**Comment by lancelet** [comment]
Hi David,

Thanks for fixing the pom hash - it looks like that is correct now.  However, xsbt (/sbt 0.10.0) is now complaining about the sha1 hash for the jar file itself (as opposed to the pom file above):

[warn]      [FAILED     ] netlib#netlib-java;0.9.3!netlib-java.jar: invalid sha1: expected=7bb0e2d87e245327339a0add7067666c41ecd95d computed=1d41b60e5180f6bcb7db15e7353dde7147cd3928 (1584ms)

Is the process of calculating and uploading the hashes automated?

Thanks,

Jonathan Merritt.

**Comment by lancelet** [comment]
PS - Further information: I'm not using the new sbt just to be difficult; I'm now relying on its ability to pull down GitHub projects as dependencies, which makes life a lot easier when many of my own projects aren't big / mature enough to belong in a maven repo.

**Comment by dlwh** [comment]
No worries! It's good to stay up to date on tools...

It probably should be automatic, but I'm doing it by hand, because I don't actually have netlib 0.9.3 and I didn't care about the integrity of the pom that much (I guess dramage uploaded it?)

Anyway, I verified that google code has computed the sha1 of the jar is what you computed it as (http://code.google.com/p/netlib-java/downloads/detail?name=netlib-java-0.9.3.jar&can=2&q=), so I'm guessing it's legit. I have no idea how the sha1 ended up wrong. Fixed. Can you give it a shot.

-- David

**Comment by lancelet** [comment]
Hi David,

Thanks again - it's all working now.

Jonathan.
